apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
      - name: bid-svc
        image: trycatchlearn/bid-svc
        imagePullPolicy: Always
        env:
          - name: RabbitMq__Host
            value: rabbit-clusterip
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: rabbitUn
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: rabbitPw
          - name: ConnectionStrings__BidDbConnection
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: connString
          - name: IdentityServiceUrl
            value: https://id.trycatchlearn.com
          - name: GrpcAuction
            value: http://auction-clusterip:7777
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
  - port: 80
    targetPort: 80
